### ISSUE TITLE
Questions for homework 05

### ISSUE THREAD

**Issue by lordxist** [ps-tuebingen-courses/pl1-2018#3]
Since there will be no exercise session on Thursday, May 31, due to the holiday, please use this issue to ask questions regarding homework 05.

**Comment by fkellner** [comment]
The first question about the FAE and BCFAE programs in task 1 asks if they are 'equivalent, in the sense that if we call them with the same argument, we always get the same result?'. However, the defined programs seem to be expressions that evaluate to numerical values (and not Closure Values) and therefore do not take any arguments.

**Comment by fkellner** [comment]
Also, should something like ```scala Seq(Assign('x,Num(1)),Add('x,'x)) ``` be an error or evaluate to 2?

**Comment by lordxist** [comment]
> The first question about the FAE and BCFAE programs in task 1 asks if they are 'equivalent, in the sense that if we call them with the same argument, we always get the same result?'. However, the defined programs seem to be expressions that evaluate to numerical values (and not Closure Values) and therefore do not take any arguments.

You are right, of course. Sorry, my bad. 
For all the examples considered in the task, the following suffices:

**Two programs are equivalent if they evaluate to the same numerical value.**

> Also, should something like `Seq(Assign('x,Num(1)),Add('x,'x))` be an error or evaluate to 2?

Either way is fine.

**Comment by lordxist** [comment]
For those who follow the three step recipe ("In case you have trouble getting started..."):

I just saw that in step 3 I incorrectly referred to the `Fun` case. The description of the step is correct, but you should change the `App` case rather than the `Fun` case. Sorry!

**Comment by lordxist** [comment]
I have now fixed all problems mentioned in this issue in the file in repo `pl1-2018`:
https://github.com/ps-tuebingen-courses/pl1-2018/blob/master/exercises/05Hw.md

**Comment by AlexRzehak** [comment]
It's pretty late, but I still have a new question:
About the Assign function: What is to do, if the Symbol is not yet present in the envrionment?
Shall we create a new allocation?
Then we must use something like closures for Assign, too, or am I mistaken?
Thanks!

**Comment by lordxist** [comment]
> Shall we create a new allocation?

You can implement it that way, but you don't need to.
See [this question](https://github.com/ps-tuebingen-courses/pl1-2018/issues/3#issuecomment-393602888) above, where my answer was that throwing an error in that situation is fine.

**Comment by AlexRzehak** [comment]
Greetings,
well, sometimes reading every post carefully might be pretty useful. :)
Thanks for your quick answer!
